### PR TITLE
Fix/transaction count

### LINKED ISSUE #419: OTKExpired being counted multiple times in certain circumstances
We have an issue where expired OTKs are being counted multiple times when one of the workers attempts to delete Expired OTKs at midnight. 

Due to each service running a worker we run into a race condition where each worker is attempting to count and then delete the expired keys. 

Because the algorithm is as follows 
 - Count Keys for metrics
 - Delete keys 
 - if deletion was successful save metrics 
 
 What is happening is the counts are occurring at the same time, one deletion is happening before the other and both are successful one deletes the counted keys the other deletes nothing. Because both are successful the counts get persisted causing a miscount of OTKExpired.

### PR DESCRIPTION
**Pull request by CalvinRodo**
## Fixes:
This closes #419 by modifying how OTKs that need to be cleaned up are deleted and counted from the database. 

Previously we would count all OTKs to be deleted, attempt to delete, and then persist counts of deleted OTKs. This caused an issue were deleted keys were being counted more then once. 

## Description of what your PR accomplishes:

Breaks up the expiration worker deletion so it now counts and deletes Expired, Exhausted, and Unclaimed OTKs separately. 

The count and deletion now occur in a transaction this should prevent the race condition that was previously found in this worker. 

## Why this approach? Any notable design decisions?

This was the simplest approach without having to modify our ATO. 

 We also could have broken the expiration worker out into a microservice/lambda that runs on a schedule and runs cleanup tasks but this would have created a modification to the approved architecture and potentially require a modification of ATO. Arguably this is the "better" solution for this problem, we will add it to the backlog to work on if time permits. 

## Anything the reviewers should focus on? Any discussion points?

Make sure it actually works and test coverage is sufficient.

### CODE REVIEW

**Review by tpjods — APPROVED** [review]
Thank you for the walk through! Ship It!

**Comment by maxneuvians** [comment]
No Code review but functionality tests passed:

6 new keys generated, then backdated 24 hours:
Screen Shot 2021-01-21 at 12 26 02 PM

Screen Shot 2021-01-21 at 12 26 12 PM

5 new keys generated and claimed, then `remaining_keys` set to 0 (aka exhausted):
Screen Shot 2021-01-21 at 12 27 35 PM

Screen Shot 2021-01-21 at 12 27 52 PM

5 new keys generated and claimed, then backdated more than 15 days:
Screen Shot 2021-01-21 at 12 29 32 PM

Screen Shot 2021-01-21 at 12 29 57 PM

events table show all the correct counts for creation, claiming, and deletion events

File: pkg/persistence/events_test.go [hunk 1]
```diff
@@ -65,16 +63,21 @@ func Test_SaveEvent(t *testing.T) {
...
 		Count:      1,
 		DeviceType: Server,
 		Date:       time.Now(),
 	}
 
+	mock.ExpectBegin()
 	setupSaveEventMock(mock, event)
 
-	saveEvent(db, event)
+	event.Originator = token1
```
Comment (maxneuvians) [inline pkg/persistence/events_test.go:75]: it looks like this line is reverting the code on line 66, was there a specific reason for the change on 66?

**Review by maxneuvians — APPROVED** [review]
LGTM - I assume that `tx *sql.Tx` will have type caught any remaining `saveEvent` that were still using `db *sql.Db` so we should be safe on that change.

File: pkg/persistence/events_test.go (hunk 1 above)
Comment (CalvinRodo) [reply pkg/persistence/events_test.go:75]: So I don't really know what caused the change to break this test. 

But this is what is happening: 

`token1` gets translated to `"ONApi"` in the saveEvent method so the expectation created in setupSaveEventMock needs the translated version of the token. Then I have to set it back to token1 so that the method can do the translation. 

If I revert  back the test fails and you get the following error: 

_Expected nil, but got: &errors.errorString{s:"ExecQuery '\n\t\tINSERT INTO events\n\t\t(source, identifier, device_type, date, count)\n\t\tVALUES (?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE count = count + ?', arguments do not match: argument 0 expected [string - aaaaaaaaaaaaaaaaaaaa] does not match actual [string - ONApi]"}_
