### PR TITLE
fix: drop old duration table replace with new one

### LINKED ISSUE #428: Fix OTK Duration bucket bug
- [ ] Change otk_duration table to use hours & originator as unique ID instead of date & originator
- [ ] Clean up database and remove inaccurate historical data (to be preserved in google sheets)
- [ ] Update Tests

### PR DESCRIPTION
**Pull request by CalvinRodo**
fixes #428 

## Description of what your PR accomplishes:

This PR adds a migration that will drop the otk_life_durations table and create a new one in it's place that uses the `originator` and `hours`  as a unique key constraint on the table instead of `originator` and `duration`

## Why this approach? Any notable design decisions?

As the data we previously captured is essentially worthless due to this bug and we cannot re-generate the actual metrics dropping the table and recreating it through a migration is the easiest solution to this bug. 

## Anything the reviewers should focus on? Any discussion points?

Make sure that migration works.

### CODE REVIEW

File: pkg/persistence/migrator.go [hunk 1]
```diff
@@ -132,6 +132,21 @@ CREATE TABLE IF NOT EXISTS otk_life_duration (
...
+DROP TABLE otk_life_duration
+`,`
+CREATE TABLE IF NOT EXISTS otk_life_duration (
+	originator	VARCHAR(32) 	NOT NULL,
+	hours		INT				NOT NULL,
+	date		DATE			NOT NULL,
+	count		INT				UNSIGNED NOT NULL DEFAULT 0,
+	INDEX (originator),
+	INDEX (hours),
+	UNIQUE KEY originator_hours(originator, hours)
```
Comment (CalvinRodo) [inline pkg/persistence/migrator.go:149]: Formatting is tabs and looks fine in an IDE, I'll do a follow up PR sometime fixing formatting in this file

**Review by maxneuvians — APPROVED** [review]
Looks good to me
