### PR TITLE
Go tests

### LINKED ISSUE #151: CI fails after 8 PM EST
These errors come up after 8 PM EST reliable when running tests:

```
  1) Failure:
RoundtripTest#test_key_roundtrip [/home/runner/work/covid-shield-server/covid-shield-server/test/roundtrip_test.rb:103]:
  (from /home/runner/work/covid-shield-server/covid-shield-server/test/roundtrip_test.rb:55:in `test_key_roundtrip').
--- expected
+++ actual
@@ -1 +1 @@
-["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l"]
+["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "z"]
```

and 

```
 2) Failure:
UploadTest#test_invalid_sequencing [/home/runner/work/covid-shield-server/covid-shield-server/test/lib/helper.rb:102]:
Expected: 200
  Actual: 500
```

### PR DESCRIPTION
**Pull request by maxneuvians**
Adds units tests for Go.

Also closes #151 and addresses parts of #55.

Apologies to the reviewer. There are a lot changed files in here. The good news is that none of them actually apply to the actual application code as they only test the code. This means that one strategy for review is to just make sure no actual application code is touched! 

The current code coverage looks like this:

```
?       github.com/CovidShield/server/pkg/app   [no test files]
?       github.com/CovidShield/server/pkg/config        [no test files]
?       github.com/CovidShield/server/pkg/expiration    [no test files]
ok      github.com/CovidShield/server/pkg/keyclaim      (cached)        coverage: 100.0% of statements
ok      github.com/CovidShield/server/pkg/persistence   0.023s  coverage: 67.4% of statements
ok      github.com/CovidShield/server/pkg/proto/covidshield     (cached)        coverage: 6.9% of statements
ok      github.com/CovidShield/server/pkg/retrieval     (cached)        coverage: 84.2% of statements
ok      github.com/CovidShield/server/pkg/server        (cached)        coverage: 92.6% of statements
?       github.com/CovidShield/server/pkg/telemetry     [no test files]
ok      github.com/CovidShield/server/pkg/timemath      (cached)        coverage: 100.0% of statements
```

Some code was not tested because it isn't critical to the application logic. Ensuring more test coverage would further delay the PR. Currently all critical business logic is covered by the tests in Go and whatever remains is covered by the already existing Ruby integration tests.

If you would like to see a complete line by line coverage you can run the following:

```
go test -coverprofile=coverage.out ./pkg/...
go tool cover -html=coverage.out -o=out.html
```

and then opening `out.html` in a browser. 

Here are a couple idea for improvement:

- Add coverage for some of them missing bit and bobs that are not critical business logic
- The tests are very verbose, especially when it comes to common `assert` blocks. Ex:
```
assert.Equal(t, 200, resp.Code, "success response is expected")
assert.True(t, checkClaimKeyResponseError(resp.Body.Bytes(), pb.KeyClaimResponse_NONE))
assert.True(t, checkClaimKeyResponseTriesRemaining(resp.Body.Bytes(), uint32(triesRemaining)))
```
The blocks happen over and over again with slightly different params and could be collapsed into one `assert_resp` function which takes all the params, ex: `assert_resp(statusCode, bodyCompare, errorCompare)` and does one check.

 ~It is a similar story for asserting logs:~
```
assert.Equal(t, 1, len(hook.Entries))
assert.Equal(t, logrus.WarnLevel, hook.LastEntry().Level)
assert.Equal(t, "error recording claim-key success", hook.LastEntry().Message)
```

~could be made into `assert_log(len, level, msg)`.~ DONE!

Also we should look into installing an automatic coverage either using coveralls or code climate.

### CODE REVIEW

File: pkg/config/config.go [hunk 1]
```diff
@@ -38,11 +38,11 @@ func InitConfig() {
 	viper.SetConfigType("yaml")
 	setDefaults()
 	if err := viper.ReadInConfig(); err != nil {
-		log(nil, err).Fatal("Error reading application configuration file")
+		log(nil, err).Error("Error reading application configuration file")
 	}
 	err := viper.Unmarshal(&AppConstants)
 	if err != nil {
-		log(nil, err).Fatal("Unable to unmarshal the application configuration file")
+		log(nil, err).Error("Unable to unmarshal the application configuration file")
```
Comment (CalvinRodo) [inline pkg/config/config.go:45]: Are these changes supposed to be here?

Comment (maxneuvians) [reply pkg/config/config.go]: Great catch - I think this was me messing with log level and testing for them
